### PR TITLE
Members API changes for frontend

### PR DESCRIPTION
**Pull request by lebe1**
- Adds small changes in the API for users profile
- Should be merged after [PR 13](https://github.com/MILA-Wien/collectivo-ux/pull/13) in collectivo-ux repository

### CODE REVIEW

**Comment by JoelForamitti** [comment]
Hi, the changed field will be removed in #36. However, there will be many boolean fields in the future. Is boolean not possible for the frontend?

**Comment by lebe1** [comment]
Yes it is possible but in this case it was quite a pain to translate a Boolean 'true' to a String 'Yes' for the frontend, retranslate it for the API-call to the backend instead of and I prefer a [list of two options](https://primefaces.org/primevue/listbox) visually more than a [RadioButton](https://primefaces.org/primevue/radiobutton) of two options or a [Switch](https://primefaces.org/primevue/inputswitch).
But I guess we should discuss about it a little bit tomorrow :)

**Comment by JoelForamitti** [comment]
The input type is checkbox, right? Then it would be this one: https://primefaces.org/primevue/checkbox

**Comment by lebe1** [comment]
And I forgot this [one, the SelectButton](https://primefaces.org/primevue/selectbutton). This is my preferred choice for booleans in PrimeVue.

**Comment by JoelForamitti** [comment]
Alright, but I'd say if the input type is checkbox the result should be a checkbox. We can add additional input types for switch etc. (select and radio we already have)

**Comment by lebe1** [comment]
This branch is no longer in use and nothing needs to be merged.

**Pull request closed without merging**
